name: "Deploy to staging"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to the staging server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        run: |
           echo "${{ secrets.PRIVATE_KEY }}" > private_key
           chmod 600 private_key
           file private_key
           echo private_key
          
