name: "Deploy to staging"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to the staging server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        run: |
           echo "${{ secrets.PRIVATE_KEY_B64 }}" | base64 -d > private_key
           chmod 600 private_key
           file private_key
           ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.STAGING_SERVER_IP }} << 'EOF'
           source ~/.bashrc
           echo "Connected to server"
           cd CI_CD_Testing
            git pull origin main
            node --version
            pnpm install
            pnpm run build
            pm2 restart all
            EOF
          
